version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3307 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/S09P12D209/back_end/petmily_pjt_temp/mysql/data:/var/lib/mysql