version: '3'

services:
  db:
    container_name: mysqldb
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: petmilydb
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: qwe123
      TZ: 'Asia/Seoul'
    ports:
      - "3307:3306"
    volumes:
      - data_mysqldb ~/S09P12D209/back_end/petmily_pjt_temp/mysql:/var/lib/mysqldb
    networks:
      - app-tier
    tty: true

  api-server:
    container_name: api-server
    build:
      context: ./
    command: gradle bootRun
    ports:
      - "8080:8080"
    networks:
      - app-tier
    depends_on:
      - db
    restart: on-failure
    tty: true

networks:
  app-tier:
    driver: bridge

volumes:
  data_mysqldb: null